### ISSUE TITLE
Fail when install from cmd

### ISSUE THREAD

**Issue by CamposErik** [CamposErik/React-Native-Silent-Ping-SMS#2]
When I try to install with this:

npm install react-native-silent-ping-sms --save

It gives an error when trying to install from cmd.

npm ERR! code E404
npm ERR! 404 Not Found: react-native-silent-ping-sms@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\erikc\AppData\Roaming\npm-cache\_logs\2019-01-10T12_05_55_770Z-debug.log

This is the log.

info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\erikc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'react-native-silent-ping-sms',
1 verbose cli   '--save' ]
2 info using npm@6.5.0
3 info using node@v11.6.0
4 verbose npm-session d26f21a0098a831f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/react-native-silent-ping-sms 3085ms
8 silly fetchPackageMetaData error for react-native-silent-ping-sms@latest 404 Not Found: react-native-silent-ping-sms@latest
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 26679ms
11 verbose stack Error: 404 Not Found: react-native-silent-ping-sms@latest
11 verbose stack     at fetch.then.res (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
11 verbose stack     at _drainQueueStep (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
11 verbose stack     at _drainQueue (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
11 verbose stack     at Async._drainQueues (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\erikc\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at processImmediate (timers.js:632:19)
12 verbose cwd C:\Users\erikc\flyve-mdm\ReactNative\RNproject1\practica
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\erikc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-native-silent-ping-sms" "--save"
15 verbose node v11.6.0
16 verbose npm  v6.5.0
17 error code E404
18 error 404 Not Found: react-native-silent-ping-sms@latest
19 verbose exit [ 1, true ]

**Comment by CamposErik** [comment]
Upload it to NPM
cd/path/to/package
npm publish

**Comment by CamposErik** [comment]
Everything is okey, it is already published.

[https://www.npmjs.com/package/react-native-silent-ping-sms](url)
